name: CurrencyConverter
options:
  bundleIdPrefix: com.сurrencyсonverter
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.6.0
  SwifterSwift:
    url: https://github.com/RomanPodymov/SwifterSwift
    branch: master
targets:
  iOSApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources]
    info:
      path: Sources/Info.plist
    dependencies:
      - package: SnapKit
      - package: SwifterSwift
